export const OASIS_TOOLBAR_ITEMS = {
  fileDropdown: "editor-toolbar-file-dropdown",
  exportDocx: "editor-toolbar-export-docx",
  exportPdf: "editor-toolbar-export-pdf",
  importDocument: "editor-toolbar-import-document",
  undo: "editor-toolbar-undo",
  redo: "editor-toolbar-redo",
  style: "editor-toolbar-style",
  fontFamily: "editor-toolbar-font-family",
  fontSize: "editor-toolbar-font-size",
  color: "editor-toolbar-color",
  highlight: "editor-toolbar-highlight",
  textShading: "editor-toolbar-text-shading",
  bold: "editor-toolbar-bold",
  italic: "editor-toolbar-italic",
  underlineControl: "editor-toolbar-underline-control",
  strike: "editor-toolbar-strike",
  superscript: "editor-toolbar-superscript",
  subscript: "editor-toolbar-subscript",
  insertImage: "editor-toolbar-insert-image",
  insertTable: "editor-toolbar-insert-table",
  link: "editor-toolbar-link",
  unlink: "editor-toolbar-unlink",
  footnote: "editor-toolbar-footnote",
  imageAlt: "editor-toolbar-image-alt",
  alignLeft: "editor-toolbar-align-left",
  alignCenter: "editor-toolbar-align-center",
  alignRight: "editor-toolbar-align-right",
  alignJustify: "editor-toolbar-align-justify",
  bulletList: "editor-toolbar-list-bullet",
  orderedList: "editor-toolbar-list-ordered",
  outdent: "editor-toolbar-list-outdent",
  indent: "editor-toolbar-list-indent",
  listOptions: "editor-toolbar-list-options",
  lineSpacing: "editor-toolbar-line-spacing-control",
  metrics: "editor-toolbar-metrics",
  table: "editor-toolbar-table",
  section: "editor-toolbar-section",
} as const;

export type OasisToolbarItemId =
  (typeof OASIS_TOOLBAR_ITEMS)[keyof typeof OASIS_TOOLBAR_ITEMS];
