export const OASIS_MENU_ITEMS = {
  fileNew: "file_new",
  fileImport: "file_import",
  fileSave: "file_save",
  fileExport: "file_export",
  fileExportPdf: "file_export_pdf",
  fileExportDocx: "file_export_docx",
  filePrint: "file_print",
  editUndo: "edit_undo",
  editRedo: "edit_redo",
  editCopy: "edit_copy",
  editFind: "edit_find",
  editSelectAll: "edit_selectAll",
  viewMargins: "view_margins",
  viewParagraphMarks: "view_paragraph_marks",
  viewPreciseFonts: "view_precise_fonts",
  insertImage: "insert_image",
  insertImageCaption: "insert_image_caption",
  insertTable: "insert_table",
  insertLink: "insert_link",
  insertFootnote: "insert_footnote",
  insertPageBreak: "insert_pageBreak",
  formatText: "format_text",
  formatTextBold: "format_text_bold",
  formatTextItalic: "format_text_italic",
  formatTextUnderline: "format_text_underline",
  formatTextStrike: "format_text_strike",
  formatAlign: "format_align",
  formatAlignLeft: "format_align_left",
  formatAlignCenter: "format_align_center",
  formatAlignRight: "format_align_right",
  formatAlignJustify: "format_align_justify",
  formatLists: "format_lists",
  formatListsBullet: "format_lists_bullet",
  formatListsNumbered: "format_lists_numbered",
} as const;

export type OasisMenuItemId =
  (typeof OASIS_MENU_ITEMS)[keyof typeof OASIS_MENU_ITEMS];
