export const OPERATION_TYPES = {
  INSERT_TEXT: 'INSERT_TEXT',
  DELETE_BACKWARD: 'DELETE_BACKWARD',
  DELETE_FORWARD: 'DELETE_FORWARD',
  SET_SELECTION: 'SET_SELECTION',
  TOGGLE_MARK: 'TOGGLE_MARK',
  SET_BLOCK_ALIGNMENT: 'SET_BLOCK_ALIGNMENT',
  INSERT_SECTION_BREAK: 'INSERT_SECTION_BREAK',
  SET_SECTION_TEMPLATE: 'SET_SECTION_TEMPLATE',
  APPEND_PARAGRAPH: 'APPEND_PARAGRAPH',
};
