// @ts-nocheck








export const OPERATION_TYPES = {
  APPEND_PARAGRAPH: "APPEND_PARAGRAPH",
  SET_SECTION_TEMPLATE: "SET_SECTION_TEMPLATE",
  SET_SELECTION: "SET_SELECTION",
  INSERT_TEXT: "INSERT_TEXT",
  DELETE_TEXT: "DELETE_TEXT",
  INSERT_PARAGRAPH: "INSERT_PARAGRAPH",
  MOVE_SELECTION: "MOVE_SELECTION",
  TOGGLE_MARK: "TOGGLE_MARK",
};
